import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script';
import 'bootstrap/dist/css/bootstrap.min.css';
import ApiCall from '@/app/Storage/ApiCall';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApiCall>{children}</ApiCall>
        
        </body>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"
      ></Script>
    </html>
  )
}
